apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/alicloud-loadbalancer-address-type: internet
    service.beta.kubernetes.io/alicloud-loadbalancer-id: ***
  labels:
    app: gateway
  name: gateway
  namespace: face
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8888
  selector:
    app: gateway
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: gateway
  name: gateway
  namespace: face
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        image: registry-vpc.cn-hangzhou.aliyuncs.com/***
        imagePullPolicy: Always
        name: gateway
        ports:
          - containerPort: 8888
            protocol: TCP
      imagePullSecrets:
        - name: registrykey