apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway
  namespace: face
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: gateway
        image: registry-vpc.cn-hangzhou.aliyuncs.com/***
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
          protocol: TCP
      imagePullSecrets:
      - name: registrykey