apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 5
  template:
    spec:
      containers:
      - name: gateway
        resources:
          limits:
            cpu: "2048m"
          requests:
            cpu: "1024m"